services:
  postgres:
    image: postgres:15
    container_name: docuquery_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: docuquery
      POSTGRES_PASSWORD: docuquery
      POSTGRES_DB: docuquery
    ports:
      - 5400:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  tika:
    image: apache/tika:latest
    container_name: tika
    ports:
      - "9998:9998"

  paddleocr:
    image: paddlecloud/paddleocr:2.6-cpu-latest
    container_name: paddleocr
    ports:
      - "8000:8000"
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

volumes:
  postgres_data: